### ISSUE TITLE
JavaScript Error when using IE: Unable to get property 'apply'

### ISSUE THREAD

**Issue by AmrineA** [MarkPieszak/aspnetcore-angular2-universal#150] opened 2017-04-04 17:30 UTC
![image](https://cloud.githubusercontent.com/assets/6352189/24670045/9b41d12e-193a-11e7-94ab-8782d3b4392d.png)
When trying to run the default application, I get the error seen above. Using Chrome, this error doesn't show. From the research I've done, it appears that .apply() is not available in IE and needs some sort of shim to work properly. I've tried some of the suggestions, but haven't been able to get it to work.

**Comment by MarkPieszak** [comment] 2017-04-04 18:38
What version of IE?
I just made a major major update #151  (we now have AoT support and bunch of other things).

Can you wipe out the project and get latest?

Inside `/Client/polyfills/` you'll see `polyfills.ts` this is similar to the one found in Angular-CLI for example.
You'll see some comments about providing shims for older browsers, you'd want to uncomment out a bunch of those `core-js/**` lines to get IE9-11 support.

Hope that helps!

**Comment by AmrineA** [comment] 2017-04-04 18:44
Thanks, I'll pull down the latest, take a look and report back.

**Comment by AmrineA** [comment] 2017-04-04 19:18
I've pulled down the latest, uncommented those lines in polyfills and tried running it. I'm getting completely different errors now:
![image](https://cloud.githubusercontent.com/assets/6352189/24674540/cb1ed7b6-1949-11e7-948b-2b57a8ac1f07.png)
After hitting F5 a couple of times:
![image](https://cloud.githubusercontent.com/assets/6352189/24674558/d9b723fa-1949-11e7-8b6b-c47f3b748e79.png)
I forgot to mention that I was testing things in IE11 before. I noticed that the webpack.config.vendor.js is gone now. How does the vendor.js file get built or is that gone?

**Comment by MarkPieszak** [comment] 2017-04-04 20:09
It's gone now actually. I'll probably bring something similar back but it won't be so manual of a process.

Can you wipe out both the dist folders and do the below, just to see if anything is acting up?

    npm run build:dev -- --verbose

**Comment by rphilp** [comment] 2017-04-04 20:36
I think the issue is that node-sass and sass-loader are missing from package.json. I just installed them and then it worked.

Just to confirm the fix for this issue. Removing the comments for the IE9-11 imports does work.

Next time slow down with the fixes. :)

**Comment by MarkPieszak** [comment] 2017-04-04 22:11
NgConf tomorrow 🙈🎁 had to get it ready and you're right I had those installed but not saved.
Want to make a quick PR to add them in the dependencies? @rphilp

**Comment by rphilp** [comment] 2017-04-04 22:36
I believe I dropped the PR with the dependencies. First time doing that though so apologies if I messed it up.

**Comment by MarkPieszak** [comment] 2017-04-04 23:27
Don't see it @rphilp 
It's ok I can add it in there

**Closed** 2017-04-05 00:17 UTC
Labels: Needs Investigation
