### ISSUE TITLE
Prerendering failed because of error: SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by vmural** [MarkPieszak/aspnetcore-angular2-universal#479] opened 2017-11-13 21:45 UTC
I have this problem, publish on IIS

Prerendering failed because of error: SyntaxError: Invalid regular expression: /^[_A-Za-zÀ-ÖØ-öø-˿Ͱ-ͽͿ-῿‌-‍⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-��-󯰀-�:][-._A-Za-z0-9·À-ÖØ-öø-˿̀-ͽͿ-῿‌‍‿⁀⁰-↏Ⰰ-⿯、-퟿豈-﷏ﷰ-��-󯰀-�:]*$/: Range out of order in character class

**Comment by alexbenitez** [comment] 2017-11-14 04:22
I think this is a duplicate of this [https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/460 ](https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/460 ).

**Comment by isaac2004** [comment] 2018-01-04 16:36
duplicate of #460

**Closed by isaac2004** 2018-01-04 16:36 UTC
