### ISSUE TITLE
Webpack / CLI errors while publishing

### ISSUE THREAD

**Issue by dguisinger** [MarkPieszak/aspnetcore-angular2-universal#220] opened 2017-04-26 04:20 UTC
I'm getting the following output, any ideas?
Its running just fine when I run the project, I just can't publish it...

```
node node_modules/webpack/bin/webpack.js --env.aot --env.client
Running build for client with AoT Compilation
Hash: c57ee1028f0785bfc036
Version: webpack 2.2.1
Child
    Hash: c57ee1028f0785bfc036
    Time: 16464ms
                  Asset     Size  Chunks                    Chunk Names
        main-browser.js  1.15 MB       0  [emitted]  [big]  main-browser
    main-browser.js.map  1.42 MB       0  [emitted]         main-browser
       [0] ./~/rxjs/Observable.js 5.45 kB {0} [built]
      [28] (webpack)/buildin/global.js 509 bytes {0} [built]
      [29] ./~/@angular/core/@angular/core.es5.js 461 kB {0} [built]
      [46] ./~/rxjs/Subject.js 5.62 kB {0} [built]
      [53] ./Client/$$_gendir async 160 bytes {0} [built]
      [72] ./~/@angular/platform-browser/@angular/platform-browser.es5.js 142 kB {0} [built]
      [73] ./Client/polyfills/browser.polyfills.ts 128 bytes {0} [built]
      [74] ./~/@angular/common/@angular/common.es5.js 131 kB {0} [built]
      [75] ./Client/polyfills/polyfills.ts 1.2 kB {0} [built]
     [130] ./~/reflect-metadata/Reflect.js 48.2 kB {0} [built]
     [133] ./~/rxjs/SubjectSubscription.js 1.4 kB {0} [built]
     [160] ./~/rxjs/observable/merge.js 128 bytes {0} [built]
     [172] ./~/rxjs/operator/share.js 923 bytes {0} [built]
     [188] ./~/zone.js/dist/zone.js 96.1 kB {0} [built]
     [189] ./Client/main.browser.ts 1.04 kB {0} [built]
        + 175 hidden modules
    
    ERROR in Expected 'styles' to be an array of strings.
    
    ERROR in ./Client/main.browser.ts
Module not found(0,0): Error : Can't resolve './$$_gendir/app/browser-app.module.ngfactory' in 'D:\Users\dguisinger\git\ClientWebsite\Client'
     @ ./Client/main.browser.ts 4:0-89
D:\Users\dguisinger\git\ClientWebsite\ClientWebsite.csproj(96,5): Error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.aot --env.client" exited with code 2.

```

**Comment by MarkPieszak** [comment] 2017-04-26 12:32
Did you change webpack config or add a styles property some component that isn't a string? Any styleUrls get automatically converted.

Any ideas?

**Comment by dguisinger** [comment] 2017-04-26 14:39
Not that I can find; I copied all of your webpack files back over the top of mine just to be sure.

Is there fundamentally something different going on when the project does a publish than when I run the following from the command line?

```
npm run build:dev
```

Because that works just fine.  I'm not sure why the styles error message would appear for 
```
node node_modules/webpack/bin/webpack.js --env.aot --env.client
```

and not the other

**Comment by TimHarker** [comment] 2017-04-26 14:47
Same deal at this end, I'll be taking a closer look today...  so I'll report back my findings also.  Now what did I change?  Then again, might be easier to look at what I didn't change, ;-).

**Comment by MarkPieszak** [comment] 2017-04-26 15:03
The only difference is its doing AoT, but strangely enough I've never seen that error pop up in the repo. I'll have more time in a few days, I'll spend a whole day fixing up the numerous outstanding issues. If anyone can spot them sooner, that'd be great as well! I'm computer-less currently 😁

**Comment by dguisinger** [comment] 2017-04-26 15:40
Is there anything special i should be searching for in my component style references?  It's just weird,  I would have expected Webpack or Angular to encounter it already in normal project usage

**Comment by TimHarker** [comment] 2017-04-26 15:47
My error is the same, but in `TS2307 Cannot find module './ngfactory/app/server-app.module.ngfactory'. main.server.aot.ts`...
![image](https://cloud.githubusercontent.com/assets/5775607/25443470/ed7e5ae2-2a75-11e7-9a34-7a455beaebb1.png)

**Comment by TimHarker** [comment] 2017-04-26 18:51
I can reproduce the problem by simply downloading the latest version of the repository, building it in vs2017 (and subsequently running it successfully), and then trying to publish it...  bang!  Can't find module.

**Comment by TimHarker** [comment] 2017-04-26 19:22
Dropped back to April 18th version, and it published successfully...  something broke it along the way!

**Comment by M-R-Bishop** [comment] 2017-04-26 19:29
@TimHarker Yep, I'm seeing the same on production publish.  Let me know if you find out what I need to revert.

**Comment by TimHarker** [comment] 2017-04-26 19:33
I got 5 on April 19th to review...  it's something on that day, maybe long file names???

**Comment by MarkPieszak** [comment] 2017-04-26 19:49
If you run npm run build:aot the same error appears?
Just looked at commits not sure why that's appearing suddenly either. 
We did a zone bump, ms build clean additions, otherwise nothing really stands out, those tsconfigs etc weren't touched.

**Comment by TimHarker** [comment] 2017-04-26 20:16
[I believe this is the one where it all began!](https://github.com/MarkPieszak/aspnetcore-angular2-universal/tree/36df54aa9963ec366ad0dbe194568b06a60972fb)

**Comment by M-R-Bishop** [comment] 2017-04-26 20:18
In my case I'm seeing this in my main-browser.js prod output


![image](https://cloud.githubusercontent.com/assets/26702618/25454903/9162e05c-2a93-11e7-915e-fdc93135f188.png)

**Comment by MarkPieszak** [comment] 2017-04-26 20:42
So there must of been errors during AoT compilation, but to me it looks like these caused errors:

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/app/containers/users/users.component.ts#L30-L31

You can't use private properties or methods in a template, hence erroring the AoT compilation, causing this error of not finding NgModule. Not by a computer but can someone see if that fixes it?

**Comment by TimHarker** [comment] 2017-04-26 20:55
Making them public fixed it!

**Comment by dguisinger** [comment] 2017-04-26 21:03
Shoot, my app doesn't contain that part of the code

**Comment by dguisinger** [comment] 2017-04-26 23:19
So I did some more playing, I updated everything in my package.json where I could find newer versions, I'm now running on Angular 4.1.0.

The error is no longer about "ERROR in Expected 'styles' to be an array of strings".
Now its telling me my templates don't exist.

So here is a question, all of my templates and styles at some point were converted over to:
```
template: require('./templatename.html'),
styles: [require('./stylename.css')]
```

Is this no longer a valid way of doing things?  I don't remember why I did, I assume it was webpack related but its been a few months.  I see you are using the original method of templateUrl in your code.

Thoughts?

**Comment by MarkPieszak** [comment] 2017-04-27 02:44
If you're using ngtools/webpack like we are here it might be interrupting that flow, requiring the template then automatically requiring again (?) saying the template doesn't exist. You can just do things the normal way, ngtools handles all the rest now 😀

**Comment by dguisinger** [comment] 2017-04-27 06:15
Well, that "sort of" fixed it.  It got me further.  Infact, from Visual Studio, I can now publish... which means there should be no issue with the code....

Here's my new problem, if I try pushing the code to my build server, which uses a stock microsoft/aspnetcore-build docker image to run a build, I get the following:

```
error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.aot --env.client" exited with code 2.
```

But when I scroll up through the logs, nothing indicates an error anywhere during the build process.... In-fact the entire AoT build looks to have completed, the last page matches the last page of what I get when it runs locally on my development machine.

Has anyone else tried building under a linux environment yet?

**Comment by M-R-Bishop** [comment] 2017-04-27 06:18
@dguisinger Try running 'npm run build:aot' via package manager console.  This gave me a lot more detailed errors about what was failing during AoT building - I'm still working my way through all the errors.  Apparently AoT is a expert level beast to slay.

**Comment by MarkPieszak** [comment] 2017-04-27 11:18
It's quite the beast :)
Yes you definitely want to test it out from time to time to see what's missing / erroring.
Soon AoT will be the only compilation method as well.

**Comment by MarkPieszak** [comment] 2017-04-27 11:24
https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/ad05cbc38aeb61dc5d3cbb2a2d10ca9c75c7b4c6 did you implement these Linux changes in this commit? @dguisinger

**Comment by reinhardsual** [comment] 2017-04-27 17:46
I believe it is the AOT option that caused the error.
How can I publish without AOT?

**Comment by dguisinger** [comment] 2017-04-27 18:06
@MarkPieszak I did impiment the case sensitive errors.  It looks like it runs through the entire file just fine; but this is running the docker image under AWS CodeBuild and i'm not sure if the logs have all the detail I want (they seem to be missing letters here and there when they decided to line break, odd)...   I'm going to duplicate the process in a local docker container tonight where i can interact with the console....   I'm really hoping I get this resolved soon, its been holding me back on an automated release to my test environment.  All these new tools the Angular team keeps using are driving me crazy, they finally get one stable and they move on to a new one that breaks :(

**Comment by MarkPieszak** [comment] 2017-04-27 20:05
I'm not familiar with was code build otherwise I'd try to help with it there. Does it work it normal publish builds?

**Comment by MarkPieszak** [comment] 2017-04-27 20:07
@reinhardsual prod is only AoT mode, I checked in a commit that fixes the issue so you'll be all set!

Think we can close this one out now, if anyone has other issues just open up a new specific issue 
Teamwork 🎈👍

**Closed by MarkPieszak** 2017-04-27 20:07 UTC

**Comment by dguisinger** [comment] 2017-04-27 20:32
@MarkPieszak yeah, CodeBuild lets you specify a docker image (in this case "microsoft\aspnetcore-build"), loads your code onto it, executes commands from a yml file, and then copies your artifacts off.   Once it copies the artifacts off, it destroys the docker instance... so you never have the ability to interact with it, you just see the logs in CloudWatch.

Here is what I'm doing for my build process, I think its normal...  it definitely works for ASP.NET Core web services.  There shouldn't be anything special about the process, its just running under the standard microsoft build image...

```
phases:
  pre_build:
    commands:
    - apt-get update && apt-get install -y zip
  build:
    commands:
    - dotnet restore $CODEBUILD_SRC_DIR
    - npm install
    - dotnet publish $CODEBUILD_SRC_DIR --framework netcoreapp1.1 -o $CODEBUILD_SRC_DIR/publish
```

**Comment by dguisinger** [comment] 2017-04-27 22:00
Alright, not a problem with the underlying tools :)

I boneheadedly referenced a @Angular/Forms instead of @angular/forms in one spot..... works on Windows apparently.... so it was a case sensitive issue after all
