### ISSUE TITLE
Publish Error

### ISSUE THREAD

**Issue by wilrek** [MarkPieszak/aspnetcore-angular2-universal#314] opened 2017-06-22 17:44 UTC
Error	TS2307	Cannot find module './ngfactory/app/server-app.module.ngfactory'.	ab (tsconfig project)	C:\websites\Client\main.server.aot.ts	10	Active

Error		The command "node node_modules/webpack/bin/webpack.js --env.aot --env.client" exited with code 2.	Asp2017	C:\websites\Asp2017.csproj	104

**Comment by MarkPieszak** [comment] 2017-06-22 18:39
Duplicate of #297 

Can you run `npm run build:aot` from your console and see what kind of Errors come up?
It's most likely an error while statically analyzing the code during AoT compliation. Must be some private properties being acccessed in your template, or something like that.

Give that a shot and let me know! Should help you find what's wrong. 
@wilrek

**Closed by MarkPieszak** 2017-06-22 18:39 UTC
