### ISSUE TITLE
Angular 5 - Merge or PR?

### ISSUE THREAD

**Issue by BillSheldon-HunterIndustries** [MarkPieszak/aspnetcore-angular2-universal#454] opened 2017-11-01 21:47 UTC
With the launch of Angular 5, is the plan to update the main branch via a new PR or merge the existing Angular 5 branch into the master (with appropriate updates from RC)?

**Comment by MarkPieszak** [comment] 2017-11-01 23:13
Yes I'll definitely merge it in there! Let me just make sure things are working and I'll get it in tomorrow morning 👍 Apologies on the delay.

I'll try to get HttpTransferCacheModule in there, if not I can get that in, in a later PR.

**Comment by naveedahmed1** [comment] 2017-11-02 12:28
Sounds great! HttpTransferCacheModule is much needed :)

**Comment by MarkPieszak** [comment] 2017-11-02 14:21
Merged ✨ 
but unfortunately couldn't fix ServerTransfer quickly enough, for the time being you could keep the existing Transfer technique we had already built-in to the project!

Hopefully we can figure out the root cause of why ServerTransfer is breaking server renders with ASPNET.

**Closed by MarkPieszak** 2017-11-02 14:21 UTC

**Comment by naveedahmed1** [comment] 2017-11-02 15:50
Thank you so much, but I think even the old Transfer technique is broken.
