### ISSUE TITLE
meta tags is created inside of body instead of head

### ISSUE THREAD

**Issue by consigliory** [MarkPieszak/aspnetcore-angular2-universal#68] opened 2017-01-31 08:58 UTC
```
const ogImg: MetaDefinition = {name: 'og:image', content: 'https://site.com/image.png'}
            const desc: MetaDefinition = {name: 'description', content: 'A description of the page'};
            that.meta.addTags([desc,ogImg]);
```
this will result with meta tags inside of body. 
Am I doing anything wrong here?

**Comment by MarkPieszak** [comment] 2017-01-31 19:01
@consigliory So the problem is, because .NET has total control over the Html, all we have access to is the `<app>` itself unfortunately. The MetaService works if you're using Node solely as your server, as you pass the entire index.html file, but sadly in our case it doesn't :(

If you take a look at #57 the fix is in the works though :)
But basically, eventually all of these meta & title things will be populated into an object, and then when MVC is rendering the View page, it will render them inside the _layout.cshtml.

```
    <title>@prerenderResult.Globals["pageTitle"]</title>

    <!-- meta tags -->
    <meta name="description" content='@prerenderResult.Globals["meta"]["description"]'>
    <meta name="keywords" content='@prerenderResult.Globals["meta"]["keywords"]'>

    <!-- and so on, for the remaining meta / FB: / og: / twitter: meta tags -->
    <meta name="fb:app_id" content='@prerenderResult.Globals["meta"]["fb"]["appid"]'>
```

Hoping to have that update in there sometime soon, first I need to update the webpack configurations & aspnet-prerendering to 2.0 etc (#65) but then it's next on my list!

**Closed** 2017-02-01 13:41 UTC
Labels: duplicate
