### ISSUE TITLE
Server-side rendering causes server-side error if run app from dotnet publish output

### ISSUE THREAD

**Issue by ORuban** [MarkPieszak/aspnetcore-angular2-universal#69] opened 2017-01-31 20:27 UTC
How to reproduce:

1. fork master branch 
2. go to root folder and run `dotnet publish`
3. go to publishing output folder and run `dotnet aspnetcore-angular2-universal.dll`
4. open home page
Error: An error occurred while processing your request and in logs: 
`An unhandled exception has occurred: Call to Node module failed with error: Prerendering failed because of error: Error: Cannot find module 'aspnet-prerendering'`

If disable server-side rendering (remove asp-prerender-module="Client/bootstrap-server" from the <app> component in Views/Home/Index.cshtml) all work fine.

**Comment by MarkPieszak** [comment] 2017-01-31 20:36
Is aspnet-prerendering there in `node_modules`?

**Comment by ORuban** [comment] 2017-01-31 21:37
prepublish script command in project.json already has webpack step and accordingly to logs it runs OK.
node_modules (with aspnet-prerendering) exists in source folder, but not in publish "output" folder.

**Comment by MarkPieszak** [comment] 2017-02-01 01:14
I see what the issue is and it'll be fixed in #65, I need to make sure only the server bundle is given aspnet-prerender (I can't just throw it in the vendor array, client-side can't use it, it's based on Node modules).

Let me fix that one up tomorrow and I'll let you know when it's all set! @ORuban Thanks for helping out :)

**Closed** 2017-02-02 03:29 UTC
Labels: bug, Needs Investigation
