### ISSUE TITLE
Hard to debug

### ISSUE THREAD

**Issue by MaklaCof** [MarkPieszak/aspnetcore-angular2-universal#513] opened 2017-12-07 06:23 UTC
I upgrade my project to Angular 5.0 and with that I also merge this project with mine. After that it is really hard to debug, because code is almost unreadable.
Can someone help me clarifying what (if anything) I did wrong.
This is my source code:

![devenv_2017-12-07_07-20-47](https://user-images.githubusercontent.com/1589573/33701481-320dfb9a-db1f-11e7-8680-53ae3e8b4477.png)
and this is code I can debug in Developer tools:

![chrome_2017-12-07_07-22-03](https://user-images.githubusercontent.com/1589573/33701513-593158de-db1f-11e7-982b-fac49620e196.png)

Did I merge incorrectly or is this Angular 5 thing?

I check my source maps on disk and they (content) are all the same (for Angular modules):
`{"version":3,"sources":[],"names":[],"mappings":"","file":"5.js","sourceRoot":""}`

**Comment by MarkPieszak** [comment] 2017-12-08 16:47
I haven't seen this personally yet, but for now, I'd suggest sticking with the 4.x template until we can fix the underlying issues with 5.x and SSR (mainly being AngularCompilerPlugin from ngtools/webpack), if you're not using SSR then you should be fine otherwise though.

The AngularCompilerPlugin has changed vastly compared to the AoTPlugin, so this might be an issue caused by that as well.

**Comment by MaklaCof** [comment] 2017-12-10 10:45
Currently I can not switch back. I am in no hurry. I can wait for project to switch to 5.0, and then we can figure it out, what can we do.

**Comment by EmaGht** [comment] 2017-12-12 16:04
@MaklaCof That ususally happens (in my case, at least) when you have no source-map generated for your project...
You said "merged this project with mine", make sure you have this in your tsconfig:
`"sourceMap": true,`

**Comment by MaklaCof** [comment] 2017-12-13 06:30
Thank you, but I sourceMap is true:
```
{
    "compilerOptions": {
        "moduleResolution": "node",
        "module": "es2015",
        "target": "es5",
        "downlevelIteration": true,
        "noImplicitAny": false,
        "sourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "skipDefaultLibCheck": true,
        "skipLibCheck": true,
        "allowUnreachableCode": false,      
        "lib": [
            "es2016",
            "dom"
        ],
        "types": [ "node", "gapi", "gapi.auth2" ]
    },
    "include": [
        "ClientApp"
    ],
    "angularCompilerOptions": {
        /*"preserveWhitespaces": false*/    /*TODO*/
    }
}
```
And my webpack.config.js:
```
   const clientBundleOutputDir = './wwwroot/dist';
    const clientBundleConfig = merge(sharedConfig, {
        entry: { 'main-client': './ClientApp/boot.browser.ts' },
        output: { path: path.join(__dirname, clientBundleOutputDir) },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            })
        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps         
                moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [
            // new BundleAnalyzerPlugin(),
            // Plugins that apply in production builds only
            //new webpack.optimize.UglifyJsPlugin(),                //TODO until https://github.com/aspnet/SignalR/issues/867
            new AngularCompilerPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.module.browser#AppModule'),
                exclude: ['./**/*.server.ts']
            })
        ]),
        devtool: isDevBuild ? 'cheap-eval-source-map' : false,
        node: {
          fs: "empty"
        }
    });
```

I think other lines of code does not effect source maps.
![notepad2_2017-12-13_07-25-52](https://user-images.githubusercontent.com/1589573/33924654-53b65dfc-dfd7-11e7-9c81-627f8dd8b6b1.png)

**Closed** 2017-12-22 16:18 UTC
