### ISSUE TITLE
Shouldn't the repo be renamed?

### ISSUE THREAD

**Issue by electricessence** [MarkPieszak/aspnetcore-angular2-universal#521] opened 2017-12-15 19:12 UTC
Angular2?  Might want to remove the 2.

**Comment by MarkPieszak** [comment] 2017-12-16 16:17
It's in the works, the problem is breaking lots of links through out the repos issues & the web in general. Trying to figure out what's the best way of handling all of that.

Thanks for looking out though!

Closing as duplicate of #509

**Closed by MarkPieszak** 2017-12-16 16:17 UTC
